route update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -70,77 +70,73 @@ jobs:
   deploy:
     name: Deploy to GCP VM
     runs-on: ubuntu-latest
-    # needs: [build-rust, build-webapp]  # Ensure both images are built
-
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-      
-    - id: 'auth'
-      uses: 'google-github-actions/auth@v2'
-      with:
-        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
-    - name: Create VM instance if it doesn't exist
-      run: |
-        INSTANCE_NAME=${{ secrets.GCP_INSTANCE_NAME }}
-        ZONE=${{ secrets.GCP_ZONE }}
-        MACHINE_TYPE="n1-standard-1"  # Specify your desired machine type
-        IMAGE_FAMILY="debian-11"  # Specify your desired image family
-        IMAGE_PROJECT="debian-cloud"  # Specify the project for the image family
-    
-        # Check if the VM instance exists
-        if ! gcloud compute instances describe "$INSTANCE_NAME" --zone "$ZONE" &>/dev/null; then
-          echo "Creating VM instance $INSTANCE_NAME..."
-          gcloud compute instances create "$INSTANCE_NAME" --zone "$ZONE" --machine-type "$MACHINE_TYPE" --image-family "$IMAGE_FAMILY" --image-project "$IMAGE_PROJECT"
-        else
-          echo "VM instance $INSTANCE_NAME already exists."
-        fi
-    
-        # Connect to the VM and install Docker if it's not installed
-        gcloud compute ssh "$INSTANCE_NAME" --zone "$ZONE" --command "
-          if ! command -v docker &> /dev/null; then
-            echo 'Docker not found. Installing...'
-            
-            # Download the installation script
-            curl -fsSL https://get.docker.com -o get-docker.sh
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-            # Run the installation script with --dry-run to see what would happen
-            sudo sh ./get-docker.sh --dry-run
+      - id: 'auth'
+        uses: 'google-github-actions/auth@v2'
+        with:
+          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
 
-            # Now install Docker without --dry-run
-            sudo sh ./get-docker.sh
+      - name: Create VM instance if it doesn't exist
+        run: |
+          INSTANCE_NAME=${{ secrets.GCP_INSTANCE_NAME }}
+          ZONE=${{ secrets.GCP_ZONE }}
+          MACHINE_TYPE="n1-standard-1"  # Specify your desired machine type
+          IMAGE_FAMILY="debian-11"  # Specify your desired image family
+          IMAGE_PROJECT="debian-cloud"  # Specify the project for the image family
 
-            echo 'Docker installed successfully.'
+          # Check if the VM instance exists
+          if ! gcloud compute instances describe "$INSTANCE_NAME" --zone "$ZONE" &>/dev/null; then
+            echo "Creating VM instance $INSTANCE_NAME..."
+            gcloud compute instances create "$INSTANCE_NAME" --zone "$ZONE" --machine-type "$MACHINE_TYPE" --image-family "$IMAGE_FAMILY" --image-project "$IMAGE_PROJECT"
           else
-            echo 'Docker is already installed.'
+            echo "VM instance $INSTANCE_NAME already exists."
           fi
-        "
 
-      
-    - name: Deploy Rust application
-      run: |
-        # Define your Docker image
-        IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/rust-data-fetch:latest"
+          # Connect to the VM and install Docker if it's not installed
+          gcloud compute ssh "$INSTANCE_NAME" --zone "$ZONE" --command "
+            if ! command -v docker &> /dev/null; then
+              echo 'Docker not found. Installing...'
+              
+              # Download the installation script
+              curl -fsSL https://get.docker.com -o get-docker.sh
 
-        # Connect to the VM and run the Docker container
-        gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "sudo docker run -d --restart always --name rust-data-fetch \
-          -e POSTGRES_HOST=${{secrets.GCP_SQL_HOST}} \
-          -e POSTGRES_DB= ${{secrets.POSTGRES_DB}} \
-          -e POSTGRES_USER=${{secrets.POSTGRES_USERNAME}} \
-          -e POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} \
-          -e POSTGRES_PORT=${{secrets.POSTGRES_PORT}} \
-          $IMAGE"
+              # Run the installation script
+              sudo sh ./get-docker.sh
 
-    - name: Deploy Next.js application
-      run: |
-        # Define your Docker image
-        IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bitcoin-explorer-webapp:latest"
+              echo 'Docker installed successfully.'
+            else
+              echo 'Docker is already installed.'
+            fi
+          "
 
-        # Connect to the VM and run the Docker container
-        gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "sudo docker run -d --restart always -p 3000:3000 --name bitcoin-explorer-webapp \
-          -e DB_USER=${{secrets.POSTGRES_USERNAME}} \
-          -e DB_HOST=${{secrets.GCP_SQL_HOST}}
-          -e DB_NAME=${{secrets.POSTGRES_DB}} \
-          -e DB_PASSWORD=${{secrets.POSTGRES_PASSWORD}} \
-          -e DB_PORT=${{secrets.POSTGRES_PORT}} \
-          $IMAGE"
+      - name: Deploy Rust application
+        run: |
+          # Define your Docker image
+          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/rust-data-fetch:latest"
+
+          # Connect to the VM and run the Docker container
+          gcloud compute ssh "${{ secrets.GCP_INSTANCE_NAME }}" --zone "${{ secrets.GCP_ZONE }}" --command "sudo docker run -d --restart always --name rust-data-fetch \
+            -e POSTGRES_HOST=${{secrets.GCP_SQL_HOST}} \
+            -e POSTGRES_DB=${{secrets.POSTGRES_DB}} \
+            -e POSTGRES_USER=${{secrets.POSTGRES_USERNAME}} \
+            -e POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} \
+            -e POSTGRES_PORT=${{secrets.POSTGRES_PORT}} \
+            $IMAGE"
+
+      - name: Deploy Next.js application
+        run: |
+          # Define your Docker image
+          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bitcoin-explorer-webapp:latest"
+
+          # Connect to the VM and run the Docker container
+          gcloud compute ssh "${{ secrets.GCP_INSTANCE_NAME }}" --zone "${{ secrets.GCP_ZONE }}" --command "sudo docker run -d --restart always -p 3000:3000 --name bitcoin-explorer-webapp \
+            -e DB_USER=${{secrets.POSTGRES_USERNAME}} \
+            -e DB_HOST=${{secrets.GCP_SQL_HOST}} \
+            -e DB_NAME=${{secrets.POSTGRES_DB}} \
+            -e DB_PASSWORD=${{secrets.POSTGRES_PASSWORD}} \
+            -e DB_PORT=${{secrets.POSTGRES_PORT}} \
+            $IMAGE"
+
